### PR TITLE
Fix Zshch to make it idiomatic go

### PR DESCRIPTION
**Pull request by btracey**

### CODE REVIEW

**Comment by btracey** [comment]
I don't like the random hack in F64Approx. There is one test that fails where the C value is something like 1e223, and the native value is something like 5e222. I confirmed by hand that the actual change here is not the culprit. The computation of Zshch differs by less than 3 ULP, and the rest is divergent noise. If there is a less bad hack I can change it.

**Comment by btracey** [comment]
@jonlawlor travis fails because there are no buildable files in mathext. Is there a way to fix that, or should we add buildable files to the root directory?

**Comment by jonlawlor** [comment]
I don't think that should be a problem. On the other hand I don't see a .travis.yml file so that wouldn't work. I should have it in tonight I think.

**Comment by btracey** [comment]
It's the failure for the pr in diff at the moment

**Comment by jonlawlor** [comment]
I don't see how the import in quad is supposed to work compared to the
current mathext gonum master.  Is there a different version of code you are
building against?

**Comment by kortschak** [comment]
> I don't like the random hack in F64Approx. There is one test that fails where the C value is something like 1e223, and the native value is something like 5e222. I confirmed by hand that the actual change here is not the culprit.

The joys of the world of numerical computing. I think that is fine - though a comment might be worth adding.

I don't see a failure in diff. Can you post links to the things you are seeing?

**Comment by jonlawlor** [comment]
@kortschak it is in gonum/quad, see https://travis-ci.org/gonum/quad/builds/119642287

I think the quad import is referencing a version of mathext other than what is currently in the master branch of gonum/mathext.

**Comment by btracey** [comment]
Yes, that's my fault. I misread the travis output. I'll add a comment.

**Comment by btracey** [comment]
Comment added. PTAL

**Comment by kortschak** [comment]
Why is this failing? It seems to be some ruby thing, presumably the travis infrastructure.

**Comment by jonlawlor** [comment]
I have travis builds enabled for this repo but it doesn't have a .travis.yml file in it yet.  There is a setting I can modify to have it only test when a .travis.yml file is present, I'll change it right now.

**Comment by btracey** [comment]
Would you like me to pull from master so the integration tests happen properly?

**Comment by jonlawlor** [comment]
Yes, please.

**Comment by btracey** [comment]
Great, seems to be fixed. 

PTAL

**Comment by btracey** [comment]
Ping

**Comment by kortschak** [comment]
Sorry this took so long.

LGTM

**Comment by sbinet** [comment]
Note this should be rebased before being merged...

**Comment by sbinet** [comment]
actually, a839abc should be cherry-picked on top of `master`, like I did in 83a92eb.

**Comment by btracey** [comment]
Why does this need to be rebased? The changes are independent from the commits that have happened since this has been under review

**Comment by sbinet** [comment]
I'd prefer this to be rebased otherwise it would make the history of `mathext` spaghetti-like.
and I prefer a history to be rather linear :)

**Comment by sbinet** [comment]
so, to recap:

currently, I see this:

```
$> git l
*   3f39846 (origin/fixdshch) merge from master
|\  
| *   65e7c60 (HEAD -> master, origin/master, origin/HEAD) Merge pull request #10 from gonum/go-1.7rc3
| |\  
| | * 909e75c go 1.7rc2 -> go 1.7rc3
| |/  
| *   af877ba Merge pull request #9 from gonum/go-1.6.3-and-1.7rc2
| |\  
| | * c6d5c7b go 1.7beta2 -> go 1.7rc2, go 1.6.2 -> go 1.6.3
| |/  
| *   2bbed5e Merge pull request #8 from gonum/go-1.7beta2
| |\  
| | * 7495e61 go 1.7beta1 -> go 1.7beta2
| |/  
| *   1c5d110 Merge pull request #7 from gonum/go1.7beta1
| |\  
| | * d30d98d travis: go1.7beta1
| |/  
| *   fc8ddf5 Merge pull request #5 from gonum/fix-coveralls-status
| |\  
| | * c8c4102 fix coveralls.io status flair
| |/  
| *   2b94e8f Merge pull request #4 from gonum/travis-ci
| |\  
| | * 9d18146 add build tag to fortran.go
| | * b23af47 add CI and godoc flair to readme
| | * 92fb03f add .travis.yml and test-coverage.sh
| |/  
* | fcde3f3 Fix Zshch to make it idiomatic go
|/  
*   3c904a5 Merge pull request #2 from gonum/removefort
|\  
| * 80ffb55 Remove Fortran dependence in Airy tests.
|/  
*   8fc7b8d Merge pull request #1 from gonum/addamos
|\  
| * 5bd3f94 fix package imports
| * 8bd1e78 Responded to PR comments
| * 1123a5c Responded to PR comments
| * b72dfa9 fix documentation comments
| * bca7d4f Change test pattern
| * 3ad4b10 Add copyright headers
| * f03cf84 Add Fortran-backed Airy function
|/  
* 957faec Initial commit
```

that's ugly.

cherry-picking would solve it:

``` sh
$> git remote add sbinet git://github.com/sbinet/gonum-mathext
$> git fetch --all -p
$> git checkout -b new-fixdshch master
$> git cherry-pick 83a92eb
$> git branch -m fixdshch old-fixdshch
$> git branch -m new-fixdshch fixdshch
$> git push -f master fixdshch
```

**Pull request closed without merging**
