### PR TITLE
Travis ci

### PR DESCRIPTION
**Pull request by jonlawlor**

### CODE REVIEW

**Comment by jonlawlor** [comment]
This is failing because it tries to build airy/internal/amos/amoslib, possibly because there is a go file in it.  There are a few things we could do, the easiest is to only test the airy directory and no subdirectories, but then we will have to remember to modify the tests when new packages are developed.  I'll think about it a little too.

**Comment by btracey** [comment]
That file isn't used directly anymore and it's only a convenience wrapper. We could just change it's extension, and anyone who wants to use it to test can change it back.

**Comment by kortschak** [comment]
Add a build constraint "fortran" with a TODO to remove it when 1.7 is the earliest Go version we support.

**Comment by btracey** [comment]
I think this is waiting on a fix for the Fortran issue. Is that true?

**Comment by jonlawlor** [comment]
Yes, I haven't tried it yet.  I'll give it a shot tonight.

**Comment by btracey** [comment]
No worries, just wanted to make sure I wasn't holding anything up
unknowingly

**Comment by jonlawlor** [comment]
PTAL

**Comment by btracey** [comment]
LGTM

**Pull request merged**
