### PR TITLE
fix coveralls.io status flair

### PR DESCRIPTION
**Pull request by jonlawlor**

### CODE REVIEW

**Comment by btracey** [comment]
Ah, sorry, I missed that.

**Comment by jonlawlor** [comment]
It was my mistake, I copied it off of one of the other repos (blas I think).  Must have mucked something up in it though.

**Comment by jonlawlor** [comment]
I've checked and rechecked the link, the jobs, and the coveralls status and I think there is an issue on coveralls side.  Definitely nothing wrong at gonum/mathext currently, so I'm going to merge.

**Comment by jonlawlor** [comment]
I'm not sure what is going on here, there might be an issue with coveralls interaction with the amoslib folder.  Coverage is of secondary importance to just passing the existing tests.  Still irritating though.

**Pull request merged**
